import { Toaster } from "@/components/ui/sonner"
import { Inter, Playfair_Display, JetBrains_Mono } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/**
 * Root application layout that applies global fonts, HTML attributes, and common providers.
 *
 * Renders the top-level HTML structure (`<html>` and `<body>`) with language and font classes,
 * and places a `ThemeProvider` that wraps `children` alongside a `Toaster` component.
 *
 * @param children - React nodes to render inside the application's ThemeProvider
 * @returns The top-level HTML layout containing the ThemeProvider and Toaster
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
    >
      <body>

        <ThemeProvider>{children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
